# Generated by Django 2.2.4 on 2019-10-29 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('textileapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buynow',
            old_name='state',
            new_name='state1',
        ),
    ]
